### ISSUE TITLE
Reborn v1

### ISSUE THREAD

**Issue by kasmacioma** [xapdkop/sfml-nuget_builder#2]
**To-Do:**
- [ ] Automate generating and publishing
- [ ] Split 3rd-party libs by related packages
- [ ] Simplify version choice
- [ ] Catch all errors and exceptions and handle them
- [x] Source code is unnecessary since: 1) packages generated with use of official SFML libs, 2) users can view it manually by downloading and unpacking package from nuget
